### ISSUE TITLE
On / Off switch not working

### ISSUE THREAD

**Issue by CameronGoosen** [luisllamasbinaburo/EwelinkNET#13]
We are having massive issues with eWeLink, entire companies are down. Trying to connect to the eu server to GetDevices but its failing. Is anyone else having these issues? How can we solve it?

**Comment by jlucansky** [comment]
Old keys stopped working couple of hours ago. These are working for me:
```
 APP_SECRET=4G91qSoboqYO4Y0XJ0LPPKIsq8reHdfa
 APP_ID=YzfeftUVcZ6twZw1OoVKPRFYTrGEg01Q
```

**Comment by CameronGoosen** [comment]
> 

Thank you will look into this.

**Comment by hybrid2102** [comment]
I 

> Old keys stopped working couple of hours ago. These are working for me:
> 
> ```
>  APP_SECRET=4G91qSoboqYO4Y0XJ0LPPKIsq8reHdfa
>  APP_ID=YzfeftUVcZ6twZw1OoVKPRFYTrGEg01Q
> ```

Using those values the error is gone, but the device seems to not actually switch

**Comment by hybrid2102** [comment]
@CameronGoosen any news? I get 0 devices using @jlucansky 's keys

**Comment by CameronGoosen** [comment]
> Old keys stopped working couple of hours ago. These are working for me:
> 
> ```
>  APP_SECRET=4G91qSoboqYO4Y0XJ0LPPKIsq8reHdfa
>  APP_ID=YzfeftUVcZ6twZw1OoVKPRFYTrGEg01Q
> ```

@hybrid2102 this resolved the issue for me
