### ISSUE TITLE
GetCredentials not working anymore.

### ISSUE THREAD

**Issue by alexdick86** [luisllamasbinaburo/EwelinkNET#15]
Since a few weeks the GetCredentials function doesn't work anymore. Is there a workaround or a fix I don't know?

Regards from Austria.

**Comment by tarres** [comment]
Probably also the Keys not valid anymore - see https://github.com/luisllamasbinaburo/EwelinkNET/issues/18

**Comment by luisllamasbinaburo** [comment]
Look this topic https://github.com/luisllamasbinaburo/EwelinkNET/issues/18
