### ISSUE TITLE
GetDevices throws error

### ISSUE THREAD

**Issue by abc123xxx** [luisllamasbinaburo/EwelinkNET#16]
Hello,

i am new here and test the EwelinkNET but with my credentials and region="eu" the response-content is error=0 and devicelist=[] on the GetDevices function.

The GetCredentials-Function works fine.

How can i read my devices?

Best regards

**Comment by tarres** [comment]
Are you in the correct region? And does your account show devices (like in the Ewe-Portal?

**Comment by luisllamasbinaburo** [comment]
Look this topic https://github.com/luisllamasbinaburo/EwelinkNET/issues/18
