### ISSUE TITLE
"could not open port 'COM9': PermissionError(13, 'Access is denied.', None, 5)

### ISSUE THREAD

**Issue by MagalyB12** [luisllamasbinaburo/EwelinkNET#17]
Como puedo solucionar este error? Soy nueva en esto, y ya he intentado varias cosas, es para una interfaz a una pantalla con dos modulos en tkinter

**Comment by luisllamasbinaburo** [comment]
No entiendo porque te da un error de COM9. Diría que esto es un problema de Arduino, no de la librería.
