### ISSUE TITLE
Fraamework 4.7

### ISSUE THREAD

**Issue by mrrcomp** [luisllamasbinaburo/EwelinkNET#8]
Hi 
I am trying  to reference this library but I get an errorProject '..\EwelinkNet\EwelinkNet.csproj' targets 'netstandard2.1'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.7.2'.	IotDesktop			

Can I just rebuild the Library targeting the higher Framework??

I'll wait for your response before moving forward 

Thanks

**Comment by luisllamasbinaburo** [comment]
I don't think so. The websocket library we are using is only available in NetStandard
