### ISSUE TITLE
Error on MakeNonce? 

### ISSUE THREAD

**Issue by mrrcomp** [luisllamasbinaburo/EwelinkNET#9]
Hi
Can someone Help me on the EweLink Helper MakeNonce  

RandomNumberGenerator.Fill i get error doe not contain definition for "Fill" ?

If i remark out the line i can run still connect and access the api , i read my account and can see my device but not sure if thats the reason why i cant control it? Its a GSM device and I  can get its name etc but i can't do a "TurnOn" or "TurnOff" it doesn't react to the command  at all

Thanks for any help offered
Suggestions?

**Comment by luisllamasbinaburo** [comment]
Fill method is included in standard framework
![image](https://user-images.githubusercontent.com/8978133/136123526-52a68421-e76e-489d-977a-0b2ffaa8965d.png)
